# Generated by Django 4.0.5 on 2022-07-13 20:25

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to=core.models.product_image_path),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'not made'), (2, 'made'), (3, 'pending'), (4, 'delivered'), (5, 'canceled')], default=1, verbose_name='status'),
        ),
    ]
