# Generated by Django 4.0.5 on 2022-07-13 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_product_image_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='group_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.order'),
        ),
    ]
